apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: PostgreSQL
    access: proxy
    url: postgres:5432
    database: aurore_events
    user: admin
    secureJsonData:
      password: admin
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    editable: true
